package base

import (
	"void-project/pkg/ansicli"
)

func EchoMark() {
	border := ansicli.New(ansicli.FgGreen, ansicli.BgDefault)
	content := ansicli.New(ansicli.FgGreen, ansicli.BgDefault)
	border.Println("┌───────────────────────────────────────────────────────────────────────────────────────────┐")
	border.Print("│")
	content.Print("                                       void-")
	content.SetForeground(ansicli.FgRed).Print("p")
	content.SetForeground(ansicli.FgGreen).Print("r")
	content.SetForeground(ansicli.FgYellow).Print("o")
	content.SetForeground(ansicli.FgBlue).Print("j")
	content.SetForeground(ansicli.FgMagenta).Print("e")
	content.SetForeground(ansicli.FgCyan).Print("c")
	content.SetForeground(ansicli.FgWhite).Println("t")
	border.SetForeground(ansicli.FgGreen).Println("├───────────────────────────────────────────────────────────────────────────────────────────┤")
	border.Print("│ ")
	content.SetStyle(ansicli.StyleItalic).SetForeground(ansicli.FgCyan).Print("Sū Shēngxǜ's ")
	content.Reset().SetForeground(ansicli.FgCyan).Print("void-project is a web application architecture developed in ")
	content.SetForeground(ansicli.FgBlue).Print("Go")
	content.SetForeground(ansicli.FgCyan).Println(".")
	border.SetForeground(ansicli.FgGreen).Println("├───────────────────────────────────────────────────────────────────────────────────────────┤")
	border.Print("│ ")
	content.SetForeground(ansicli.FgCyan).Print("Project repository link: ")
	content.SetStyle(ansicli.StyleBlinkSlow, ansicli.StyleUnderline, ansicli.StyleItalic).SetForeground(ansicli.FgBlue).Println("https://github.com/HyrmaeusjSoo/void-project")
	content.Reset()
	border.Println("├───────────────────────────────────────────────────────────────────────────────────────────┤")
	border.Print("│ ")
	content.SetForeground(ansicli.FgBlue).Print("银")
	content.SetForeground(ansicli.FgDefault).Print("河")
	content.SetForeground(ansicli.FgCyan).Print("系")
	content.Reset().Print(" 🌌⚛️🧬🧊🔮🗡️✡️🏞️🌈🎮🪞🫧 ")
	content.SetForeground(ansicli.FgMagenta).Print("Requests")
	content.SetForeground(ansicli.FgRed).Print(".")
	content.Reset().Print("                                 ")
	content.SetForeground(ansicli.FgGreen).Print("2023")
	content.Reset().Print("-")
	content.SetForeground(ansicli.FgYellow).Println("2025")
	border.Println("├───────────────────────────────────────────────────────────────────────────────────────────┤")
	border.Print("│                                                                  ")
	content.SetForeground(ansicli.FgWhite).Print("-")
	content.SetForeground(ansicli.FgCyan).Print("-")
	content.SetForeground(ansicli.FgMagenta).Print("-")
	content.SetForeground(ansicli.FgBlue).Print("-")
	content.SetForeground(ansicli.FgYellow).Print("-")
	content.SetForeground(ansicli.FgGreen).Print("-")
	content.SetForeground(ansicli.FgRed).Print("-")
	content.SetForeground(ansicli.FgBlack).Print("- ")
	content.SetForeground(ansicli.FgCyan).Println("Hyrmaeusj 苏")
	border.Println("└───────────────────────────────────────────────────────────────────────────────────────────┘")
}
